### ISSUE TITLE
[dados] br_tse_eleicoes

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/queries-basedosdados#119]
- [x] arquitetura tabela receitas_comite - https://docs.google.com/spreadsheets/d/1KK27efWQp6t6D01RSLp_7Jp07WXyOhrpAobfnO9z-rk/edit#gid=0

- [x] arquitetura tabela receitas_orgaos_partidario - https://docs.google.com/spreadsheets/d/1ugwsHXTmOju7VCyxTv3gbSIGDYWBVku-0bXG9cB75LU/edit#gid=0
- [x] Testar em dev
- [x] criar PR em `queries-basedosdados`
- [ ]  criar metadados

**Comment by tricktx** [comment]
1. Dahis consertou a partição da tabela receitas_orgaos_partidario, rodei novamente o dbt.
2. Aguardando a revisão novamente dele para criar os metadados e colocar em produção.

**Comment by tricktx** [comment]
- [ ] OK do @rdahis.
- [ ] Criar metadados.
- [ ] Table-approve
