### ISSUE TITLE
[dados] br_ce_fortaleza_sefin_dados_imobiliarios

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/queries-basedosdados#165]
- [x] check nos dados:
  - [x] numero de linhas
  - [x] nome de variaveis
  - [x] tipo de variável
- [x] descobrir o que significa a coluna valor
- [x] converter dados geográficos para o padrão (POINT convertido, falta Latitude e Longitude)

**Comment by laura-l-amaral** [comment]
- [ ] Subir os dados
- [ ] Verificar se inclui latitude e longitude
- [ ] Verificar nome das colunas diferente da arquitetura

**Comment by tricktx** [comment]
- [ ] Enviar para a revisão

**Comment by tricktx** [comment]
- [ ] Alterar nome do conjunto para  `br_ce_fortaleza_sefin_iptu` e subir novamente.
