### ISSUE TITLE
[dados] br_mg_belohorizonte_smfa_cadastro_imobiliario

### ISSUE THREAD

**Issue by tricktx** [basedosdados/queries-basedosdados#170]
arquitetura: https://docs.google.com/spreadsheets/d/1aU1B2HqgCjf2RNvA_DGQu_FpSWjek6_BZf4jKDSr5u4/edit?pli=1#gid=0
dados originais: https://dados.pbh.gov.br/dataset?tags=IPTU&organization=smfa&tags=belo+horizonte

**Comment by tricktx** [comment]
Arquivos auxiliares para manter a tabela de arquitetura: 
https://prefeitura.pbh.gov.br/sites/default/files/estrutura-de-governo/politica-urbana/2018/planejamento-urbano/geo_zoneam_ade_2012_a0.pdf

**Comment by tricktx** [comment]
- [ ] Terminar tratamento no python
- [ ] Usar a pipeline da cvm_fi como base
    - [ ] Incluir uma etapa de check_for_uptate.
- [ ] Modularizar mais as funções
- [ ]

**Comment by tricktx** [comment]
INITCAP:

- [ ] tipo_construtivo
- [ ] tipo_ocupacao
- [ ] tipologia
- [ ] frequencia_coleta

**Comment by tricktx** [comment]
etapas: 

- [ ] Subindo dados históricos

**Comment by laura-l-amaral** [comment]
- Problema na env pra testar localmente
- Subir dados históricos "bloqueio": Cada mês demora uma hora e meia pra subir

**Comment by laura-l-amaral** [comment]
- [ ] preencher metadados
- [ ] check para atualização
