### ISSUE TITLE
[dados] censo 2022 - novas tabelas

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/queries-basedosdados#387]

**Comment by laura-l-amaral** [comment]
atualizações

**Comment by arthurfg** [comment]
## Novas tabelas:

- [População residente, por cor ou raça, nos Censos Demográficos](https://sidra.ibge.gov.br/tabela/9605)
- [População residente, por cor ou raça, segundo o sexo e a idade](https://sidra.ibge.gov.br/tabela/9606)
- [Índice de envelhecimento, idade mediana e razão de sexo, por cor ou raça](https://sidra.ibge.gov.br/tabela/9756)
- [População indígena, por grupos de idade e sexo](https://sidra.ibge.gov.br/tabela/9608)
- [Índice de envelhecimento, idade mediana e razão de sexo da população indígena, segundo quesito de declaração](https://sidra.ibge.gov.br/tabela/9757)

**Comment by arthurfg** [comment]
## Atualizações:

**Comment by arthurfg** [comment]
# 08-01-23
- Novos dados em dev (PR https://github.com/basedosdados/queries-basedosdados-dev/pull/395). 
- Os testes passaram para quase todas as tabelas (problema na tabela `quilombolas_domicilio_pelo_menos_um_morador_quilombola_territorio_quilombola`, estou corrigindo)
## Todo:
- Rodar os testes novamente
- Subir os metadados
- Abrir PR de prod
