### ISSUE TITLE
[dados] br_cgu_beneficios_cidadao

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/queries-basedosdados#453]
**Metadados da base**

1. Descrição: A base fornece informação sobre o valor do pagamento mensal recebido por beneficiarios do Bolsa Família a partir de 2013, a nível do indivíduo.

2. Qual o nome do conjunto? `br_cgu_beneficios_cidadao`

3. Qual o nome da(s) tabela(s)? `bolsa_familia_pagamentos` 

4. Fonte original dos dados
    * Endereço: `https://portaldatransparencia.gov.br/download-de-dados/bolsa-familia-pagamentos`
    * Tem API? `Não`
    * É grátis? `Sim`
    * Cobertura espacial: `sa.br`
    * Cobertura temporal: `2013-01-01(1)2021-11-01`
    * Frequência de atualização: `month`
    * Nível de Observação (colunas que são chave primárias da tabela): 
        * `br_cgu_beneficios_cidadao.bolsa_familia_pagamentos - nome`
        * `br_cgu_beneficios_cidadao.bolsa_familia_pagamentos - cpf`
        * `br_cgu_beneficios_cidadao.bolsa_familia_pagamentos - nis`
       
5. Raspagem
    * Nível de dificuldade: `baixo`
    * Existe código semi-pronto? `sim`
    * Dificuldades de big data (alta frequência, alto volume)? `sim`

**Tarefas** (seguindo os passos da documentação [aqui](https://basedosdados.github.io/mais/colab_data/))

- [x] Baixar a pasta template e os dados originais
- [x] Preencher as tabelas de arquitetura
- [x] Revisar as tabelas de arquitetura pós correção da equipe
- [x] Escrever código de captura e limpeza de dados
- [x] Organizar arquivos brutos, se necessário
- [x] Organizar arquivos auxiliares, se necessário
- [x] Criar tabela dicionário, se necessário
- [ ] Subir tabelas no BigQuery
- [ ] Criar modelo dbt em dev e testar
- [ ] Criar modelo dbt em produção
- [ ] Enviar para o code reviews
- [ ] Criar metadados
- [ ] Fechar PR

**Comment by femdias** [comment]
**Metadados da base**

1. Descrição: A base fornece informação sobre o valor do benefício mensal recebido por beneficiarios do Auxilio Brasil, de novembro de 2021 a fevereiro de 2023, a nível do indivíduo.



2. Qual o nome do conjunto? `br_cgu_beneficios_cidadao`

3. Qual o nome da(s) tabela(s)? `auxilio_brasil` 

4. Fonte original dos dados
    * Endereço: `https://portaldatransparencia.gov.br/download-de-dados/auxilio-brasil`
    * Tem API? `Não`
    * É grátis? `Sim`
    * Cobertura espacial: `sa.br`
    * Cobertura temporal: `2021-11-01(1)2023-02-01`
    * Frequência de atualização: `month`
    * Nível de Observação (colunas que são chave primárias da tabela): 
        * `br_cgu_beneficios_cidadao.auxilio_brasil - nome`
        * `br_cgu_beneficios_cidadao.auxilio_brasil - cpf`
        * `br_cgu_beneficios_cidadao.auxilio_brasil - nis`
       
5. Raspagem
    * Nível de dificuldade: `baixo`
    * Existe código semi-pronto? `sim`
    * Dificuldades de big data (alta frequência, alto volume)? `sim`

**Tarefas** (seguindo os passos da documentação [aqui](https://basedosdados.github.io/mais/colab_data/))

- [x] Baixar a pasta template e os dados originais
- [x] Preencher as tabelas de arquitetura
- [x] Revisar as tabelas de arquitetura pós correção da equipe
- [x] Escrever código de captura e limpeza de dados
- [x] Organizar arquivos brutos, se necessário
- [x] Organizar arquivos auxiliares, se necessário
- [x] Criar tabela dicionário, se necessário
- [ ] Subir tabelas no BigQuery
- [ ] Criar modelo dbt em dev e testar
- [ ] Criar modelo dbt em produção
- [ ] Enviar para o code reviews
- [ ] Criar metadados
- [ ] Fechar PR

**Comment by laura-l-amaral** [comment]
closed by #481
