### ISSUE TITLE
[dados-atualizacao] br_ibge_pam

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/queries-basedosdados#484]
atualizar [esse conjunto](https://basedosdados.org/dataset/fc403b40-a7e1-40e7-9efe-910847b45a69?table=1fd6598f-2dfa-4f26-94bb-0d6bd4a4c873)

[tabelas de arquitetura](https://drive.google.com/drive/u/0/folders/1fZi0YqSrVDENZxBDSbwANvohMBKlSXKF)

**Comment by jeantozzi** [comment]
URLs das tabelas de arquitetura:
lavoura_permanente - https://docs.google.com/spreadsheets/d/1rlovOUcL8G-HckPH7pNEi1FbbLmHltBuGWLJTvILmrE/edit?usp=drive_link
lavoura_temporaria - https://docs.google.com/spreadsheets/d/1Y2ebUNrZTUv2x_psWpK4oTxvRxhje5K6BSKZIWBQYDM/edit?usp=drive_link
