### ISSUE TITLE
br_bd_diretorios_brasil.cnae_subclasse_2_0

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/queries-basedosdados#498]
**Metadados da base**

1. Descrição: Diretório da Classificação Nacional de Atividades Econômicas - Subclasses 2.0

2. Qual o nome do conjunto? `br_bd_diretorios_brasil.cnae_subclasse_2_0`

3. Qual o nome da(s) tabela(s)?

4. Fonte original dos dados
    * Endereço: https://concla.ibge.gov.br/classificacoes/download-concla.html
    * Tem API? `não`
    * É grátis? `não se aplica`
    * Cobertura espacial: `Brasil`
    * Cobertura temporal: `não se aplica`
    * Frequência de atualização: `unique`
    * Nível de Observação (o que representa cada linha da tabela): 
        * `<tabela> - <entidade> - <coluna>`

5. Raspagem
    * Nível de dificuldade: `baixo`
    * Existe código semi-pronto? `não`
    * Dificuldades de big data (alta frequência, alto volume)? `não`

**Tarefas** (seguindo os passos da documentação [aqui](https://basedosdados.github.io/mais/colab_data/))

- [x] Baixar a pasta template e os dados originais
- [x] Preencher as tabelas de arquitetura
- [x] Revisar as tabelas de arquitetura pós correção da equipe
- [x] Escrever código de captura e limpeza de dados
- [x] Organizar arquivos brutos, se necessário
- [x] Organizar arquivos auxiliares, se necessário
- [ ] Criar tabela dicionário, se necessário
- [ ] Subir tabelas no BigQuery
- [ ] Fazer a query para publicação dos dados
- [ ] Abrir o PR com as labels de `table-approve`e `sync-dbt_schema`

**Comment by silvaizabelle** [comment]
Arquitetura: https://docs.google.com/spreadsheets/d/1MEZGMJkxO_-CmCl4x--1sxg6DgH1dFL2E3AoXG0azZk/edit?usp=sharing

**Comment by silvaizabelle** [comment]
Pasta **br_bd_diretorios_brasil.cnae_subclasse_2_0:** https://drive.google.com/drive/folders/15B1uHIQlYCHM0fqTZk9ZldyB1JWbx5yn?usp=sharing

**Comment by laura-l-amaral** [comment]
foi utilizada para a fechar a issue #660
