### ISSUE TITLE
[fix] br_ibge_pnad

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/queries-basedosdados#506]
- [ ]  Oi, pessoal! Bom dia! Estou trabalhando com os dados da PNAD compatibilizada de 1981 a 2015 e estou usando os dados disponibilizados por vocês. Mexendo com os dados percebi que a base de dados da PNAD Domicílios de 1996 têm 330.757 linhas, número muito superior aos demais anos, enquanto que a base de dados da PNAD Pessoas de 1996 têm 331.263 linhas, ou seja, está como se cada domicílio tivesse uma única pessoa, o que claramente não é o correto. Baixando a base original no IBGE, encontrei que o número de linhas da base de PNAD Pessoas de 1996 está correto, enquanto que o número de linhas da base de domicílios seria de 105.058 linhas. Mando a mensagem para saber de vocês se de fato há um erro ou se eu que não estou conseguindo entender algo. Pergunto isso pois estou usando o merge das bases de domicílios e pessoas, e eu esperava encontrar na base final o mesmo número de linhas da base de pessoas. Somando todos os anos da PNAD de pessoas, segundo os dados do data lake de vocês temos 11.006.524 linhas de pessoas de 1981 a 2015. Porém quando faço o merge encontro 12.289.285 linhas. A única divergência que encontrei foi com relação a base da PNAD domicílios de 1996. Fico no aguardo de vocês sobre isso. Muito obrigado!

- [ ]  Muito obrigado, Patrick! Só mais um comentário sobre a base da PNAD compatibilizada. Da maneira que está compatibilizada a base de vocês o cálculo da taxa de desemprego de 1990 para trás, década de 80, fica errado. A redução das opções de empregado ou não para duas opções, 0 e 1, acabou gerando algum ruído para a década de 80, de modo que eu encontrei taxas de desemprego de aproximadamente 0.1% quando deveriam ser de aproximadamente 4 a 5%. Da década de 90 em diante os cálculos batem com as estatísticas oficiais. Esse ponto é importante porque usar a base compatibilizada de vocês acabou se tornando inviável pra mim devido a essa perda de precisão muito forte.

Att. Lucas

--- 

Link dos dados: https://www.dropbox.com/scl/fo/7ol0tprp8m312x3a21ueu/AJeRRFI4NB4jtJ3FofdHZWI?rlkey=csxsa65ojk2z6u3ton8kh72g3&dl=0

**Comment by tricktx** [comment]
Os dados foram tirados do DataZoom, entretanto, o pacote só existe em Stata. 
https://github.com/datazoompuc/datazoom_social_Stata/blob/main/PNAD/datazoom_pnad.ado

**Comment by tricktx** [comment]
# Relatório:

- Em relação aos dados: 
1.  o tratamento que a Cris faz, aparentemente os nomes das variáveis estão certinhas e não em códigos, acredito que houve um pré tratamento antes do tratamento da Cris: https://github.com/basedosdados/mais/blob/master/bases/br_ibge_pnad/code/br_ibge_pnad.py
2. A quantidade de variáveis é muito baixa relacionado aos dados originais.
3. Ele afirma que a quantidade de linhas de Pessoas está correta e realmente está.
4. Mas a quantidade de linhas de Dominilios em todos os anos está errado. Acredito que isso pode ter ocorrido devido a um drop_duplicates() que a Cris aplica na variável. Todos os anos está a baixo do valor original, exceto o ano de 1996 que ele aponta como o errado. 
5. Para o usuário, o correto para o ano de 1996 na tabela de Domicilios seria 105.058 linhas, entretanto, na base original me retorna 84.947 linhas.

**Comment by tricktx** [comment]
# Pontos a serem respondidos: 
### Pergunta ao Dahis: 

- Os dados disponibilizados foram extraídos via pacote do DataZoom? A dúvida surge, porque parece que o DataZoom renomeia as variáveis de códigos para nomes compreensíveis.

1. Segue a referência do repositório do [DataZoom](https://github.com/datazoompuc/datazoom_social_Stata/blob/main/PNAD/dct/pnad2005pes.dct) .
2. Segue também o [código](https://colab.research.google.com/drive/196S6Ofbr50kB3xI8CfrTjiTjO1uRWtZL#scrollTo=pWTyZk1up_uj) da Cris que se utiliza das variáveis com nomes compreensíveis.
