### ISSUE TITLE
[fix] br_inep_ideb

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/queries-basedosdados#562]
- [x] ~~Ajustar dados de 2013, aparentemente os códigos de id_escola não estão corretos. Um usuário reportou que alguma irregularidade na fonte original causou isso~~
- [x] Incluir testes padrão + testes personalizados

---

A nota de Matemática e Língua Portuguesa foram divulgadas usando `,` como separador decimal no ano de 2015

Tabelas com problema:

- escola
- município

**Comment by aspeddro** [comment]
Finalizado em #552
