### ISSUE TITLE
[add] Censo 2022 - 03 de Maio - Quilombolas e Indígenas, por sexo e idade

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/queries-basedosdados#563]
Incluir novos dados:
- [ ] Quilombolas e Indígenas, por sexo e idade, segundo recortes territoriais específicos - Resultados do universo

Incluir metadados:
- [ ] br_ibge_censo_2022.quilombolas_domicilio_morador_territorio_quilombola
- [ ] br_ibge_censo_2022.quilombolas_populacao_residente_municipio

**Comment by arthurfg** [comment]
- https://docs.google.com/spreadsheets/d/1wTm-GozXMdrS_Kz-uQQ2dqW9VT5jeY6d/edit#gid=1045172528
- https://docs.google.com/spreadsheets/d/1kJBAZV9Pk0GZ_DNe5vWPFI5Oadunn_Hb/edit#gid=1045172528
- https://docs.google.com/spreadsheets/d/1X_UR6LXJse8WN1Pty9T57SJWNRb-vUl5/edit#gid=1045172528
- https://docs.google.com/spreadsheets/d/1hT_bggdw_sqHe4tNRwdudcNIZAWEDNq1/edit#gid=1045172528
