### ISSUE TITLE
small fixes

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/queries-basedosdados#564]
- [ ] Ajustar nivel de observação avs
- [ ] Subir avs novamente
- [x] Ligar schedules da br_anatel_bandalarga (PR Aberto)

**Comment by tricktx** [comment]
Sobre o ajuste no nível de observação da AVS: 
- **Acredito que iremos precisar subir novamente a base.**

Quando subimos, pegamos a base através do dados abertos, segue o link: https://dados.gov.br/dados/conjuntos-dados/ivs
Nessa base, há alguns problemas: 
 -  Há duas linhas para o nível de observação, com valores distintos, segue o print: 
 - Nossos dados: 
![Image](https://github.com/basedosdados/queries-basedosdados/assets/105399231/34cdde65-4725-4ae9-947f-76513d316a02)
- Base dos dados abertos: 
![Image](https://github.com/basedosdados/queries-basedosdados/assets/105399231/810ecd85-3804-4629-8748-051101f7c9b9)

Entretanto, site oficial do Atlas da Vulnerabilidade Social permite gerar um grid com a planilha com os dados, segue o link: http://ivs.ipea.gov.br/index.php/pt/planilha
![Image](https://github.com/basedosdados/queries-basedosdados/assets/105399231/1e252529-fe09-4c66-95a7-61583df20a24)

Logo, isso demonstra que há uma incompatibilidade entre os dados do dados.gov e os dados do site oficial do atlas da vulnerabilidade. 
Precisaríamos subir os dados realmente oficiais que constam no site do gov.br e dessa forma, os dados ficarem corretos.

-----

Outra questão é que os dados entre Dev e Prod estão distintos.
Em produção, não há a coluna nome_udh, nem mesmo no storage consta.
