### ISSUE TITLE
[fix] Dados aberto da camara

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/queries-basedosdados#566]
- [x]  Apoiar na análises
- [x]  Incluir nas descrições mais contexto sobre os dados (A ideia da tabela de despesa é acrescentar que as tabelas vão ser atualizadas para o ano atual e o ano anterior)
- [x]  Fazer mini relatório da situação
- [x]  Incluir testes personalizados
- [x] Limpar testes de not_null_proportion
- [x] Avaliar situação do licitacao_contrato (aparentemente os dados estao sendo atualizados no arquivo de 2023)

--- 

PR Aberto: https://github.com/basedosdados/queries-basedosdados/pull/594

**Comment by tricktx** [comment]
# Relatório: 

* Contexto: 
Saiu uma matéria da Folha de São Paulo: https://www1.folha.uol.com.br/poder/2024/02/deputados-batem-recorde-de-gasto-com-propaganda-em-2023.shtml que consta que os deputados gastaram 84,1 milhões com propagandas em 2023. (Caso não consiga abrir o link, use esse site (https://leiaisso.net/).
Entretanto, os dados estão incorretos. Acredito que eles devem ter feito essa análise a bastante tempo e estava guardada, os dados foram sendo atualizados e consequentemente os valores mostrados na matéria estão incorretos. 

Após a última vez que eu analisei os dados, eram os mesmos da base, entretanto, com o passar do tempo, o ano de 2023 também foi atualizado e a nossa base ficou desatualizada (o ano de 2022 está certinho). 

* Nossa base: 
![Image](https://github.com/basedosdados/queries-basedosdados/assets/105399231/c199fd8c-8767-44e6-9b0b-0d388a4bd2d8)

* Dados da base original que eu acabei de baixar: 
![Image](https://github.com/basedosdados/queries-basedosdados/assets/105399231/e11ca958-0029-420e-93ca-1c95e0efa575)

---

Eu estava com receio de estar usando as métricas erradas para o processo de comparação na incompatibilidade dos dados, mas tentei checar a informação que a FSP sobre o Eunício Oliveira ter usado 494k de cota para propaganda, logo, as métricas estão corretas.
![Image](https://github.com/basedosdados/queries-basedosdados/assets/105399231/7301792b-3487-42bc-a15f-5d546b069192)

--- 

A minha ideia é atualizar os dados atuais e os dados anteriores para a tabela de despesa. Dessa forma, conseguimos solucionar o problema, uma vez que a tabela de 2022 está certa. 

---

# Avaliando situação da tabela de `licitacao_contrato`

Realmente os dados de 2024 estão sendo atualizados dentro da tabela de 2024.


* Só existe a tabela de licitacao_contrato para o ano de 2023, segue print:
![Image](https://github.com/basedosdados/queries-basedosdados/assets/105399231/c518f9f3-782b-4296-bdaf-d64fc16a74dd)

* Percebe-se que os dados de 2024 estão sendo atualizados na tabela de 2023. 
![Image](https://github.com/basedosdados/queries-basedosdados/assets/105399231/c6288bcb-5bd1-4aa6-9c7d-e72728c3884e)

Apesar dos dados estão sendo atualizados, acredita que valha a pena mandar um e-mail para eles informando, talvez nem os próprios desenvolvedores estejam ciente dessa questão.
