### ISSUE TITLE
Corrigir dicionários

### ISSUE THREAD

**Issue by laura-l-amaral** [basedosdados/queries-basedosdados#634]
Corrigir chaves duplicadas nos dicionários dos conjuntos:
- [x] br_me_rais.vinculos (fazer um check se coluna de tamanho_estabelecimento se mantém com as mesmas chaves ao longo dos anos) - https://docs.google.com/spreadsheets/d/19IykHA5dPNAqjyZpUFGqYlxrrCTTZTf8LY_I7MYY1O0/edit?usp=sharing
- [x] br_ms_sim
- [x] br_ms_sinasc
- [x] br_inep_indicador_nivel_socioeconomico
- [x] br_inep_censo_escolar
- [x] br_inep_ana
- [x] br_cnpq_bolsas
- [x] br_me_sic

a lista de chaves duplicadas estão nesse [google sheets](https://docs.google.com/spreadsheets/d/1c8khtsljduHdzwc8jIagTWtZdFu1c1cr65VP-Ktp-n0/edit#gid=1834037938)

**Comment by tricktx** [comment]
A tabela do br_ms_sim está errada. As referencias da coluna de "naturalidade" aparentemente, foram tiradas do dicionário do SINASC. Irei precisar refazer o dicionário referente a coluna de "Naturalidade". 
https://drive.google.com/file/d/14XoFX-WcA4DGg5pOs0vi-U0932hIjADd/view
