### ISSUE TITLE
[dados] Atualizar `br_tse_filiacao_partidaria`

### ISSUE THREAD

**Issue by rdahis** [basedosdados/queries-basedosdados#757]
### Contexto

Temos uma versão desatualizada desses dados até 2021 [aqui](https://basedosdados.org/dataset/e68b1cfd-ca29-4bdc-b687-424d9c59760e). De lá para cá o TSE mudou a disponibilização desses dados para uma API [aqui](https://filia2-consulta.tse.jus.br/#/principal/consultar-relacao).

Há um pacote no R já pronto para baixar [aqui](https://github.com/gabrielcaseiro/tse_filiados). Precisamos criar uma pipeline no Python.

---
- [x] Descobrir como que a api atualiza
- [x] Definir melhor abordagem de incremental model
- [x] Falar sobre possíveis  `id_municipio_tse` ids que não tem tradução nos nossos diretórios.
- [x] Melhor forma de renomear o conjunto antigo

**Comment by laura-l-amaral** [comment]
arquitetura: https://docs.google.com/spreadsheets/d/1XZ8wtysRTjos9jXY_wiFfBBwiiFuLb0I/edit?gid=2114907888#gid=2114907888

**Comment by rdahis** [comment]
Deixei alguns comentários na arquitetura.
